-- RFM_Value
-- RFM SEGMENTATION : SEGMENTING CUSTOMERS BASED ON RECENCY(R), FREQUENCY(F), MONETARY(M) SCORES
-- MAX(STR_TO_DATE(ORDERDATE,' %d/%m/%y')) AS EACH_CUSTOMERS_LAST_TRANSACTION_DATE,
-- (SELECT MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y')) FROM SALES_SAMPLE_DATA) AS BUSINESS_LAST_TRANSACTION_DATE,
SELECT 
    CUSTOMERNAME,
    ROUND(SUM(SALES),0) AS MONETARY_VALUE,
    COUNT(ORDERNUMBER) AS FREQUENCY,
    DATEDIFF(
        (SELECT MAX(STR_TO_DATE(`ORDERDATE_1`, '%d/%m/%y')) FROM sales_data_for_rfm_segmentation),
        MAX(STR_TO_DATE(`ORDERDATE_1`, '%d/%m/%y'))
        
    ) AS RECENCY
FROM `sales_data_for_rfm_segmentation`
GROUP BY CUSTOMERNAME
order by 2 desc;
-- Which month had the highest sales in 2003 
SELECT PRODUCTLINE, COUNT(ORDERNUMBER) AS FREQUENCY, ROUND(SUM(SALES),2) AS REVENUE, MONTH_ID
FROM sales_data_for_rfm_segmentation
WHERE YEAR_ID = 2003
GROUP BY 1,4
ORDER BY 3 DESC;
-- Average Customer
SELECT
    CUSTOMERNAME,
    ROUND(AVG(SALES),0) AS AVG_MONETARY_VALUE,
    COUNT(*) AS FREQUENCY,
    MAX(`ORDERDATE_1`) AS RECENCY,
    DATEDIFF(MAX(`ORDERDATE_1`), MIN(`ORDERDATE_1`)) AS RECENCYDAYS
FROM `sales_data_for_rfm_segmentation`
GROUP BY 1
order by 5 desc;
-- Which Date Has the Most Orders
WITH CTE AS (
SELECT ORDERDATE_1, COUNT(ORDERNUMBER) AS FREQUENCY, ROUND(SUM(SALES),2) AS REVENUE
FROM sales_data_for_rfm_segmentation
GROUP BY 1
ORDER BY 3 DESC)

SELECT * FROM CTE
LIMIT 1;
-- In 2004 did the highest sales occur in November 
SELECT  PRODUCTLINE, COUNT(ORDERNUMBER) AS FREQUENCY , ROUND(SUM(SALES),2) AS REVENUE , MONTH_ID
FROM sales_data_for_rfm_segmentation
WHERE YEAR_ID = 2004 AND MONTH_ID = 11
GROUP BY 1
ORDER BY 2 DESC;